spring.application.name=ariga_seiya_forum
spring.datasource.url=jdbc:postgresql://localhost:5432/ariga_seiya_forum
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=info
spring.mvc.hiddenmethod.filter.enabled=true
